### ISSUE TITLE
May ForImage utilize FIG features?

### ISSUE THREAD

**Issue by gha3mi** [AnonMiraj/fig#1]
Hello,

Thank you for sharing your project.

I have also developed a Fortran library called [ForImage](https://github.com/gha3mi/forimage) for processing and editing PNM images and managing colors, which is used by [ForColormap](https://github.com/vmagnin/forcolormap) as a dependency. I would like to inquire whether you would be interested in integrating some functionalities from your project into ForImage?

Best regards,
Ali

**Comment by AnonMiraj** [comment]
Hello Ali,

I am grateful that you found my project useful, and sure, I don't mind. 

But don't you think Fig is still too young? It is still quite basic, and I don't think it is quite mature enough as of yet.

**Comment by gha3mi** [comment]
I didn't come across your post on Discourse earlier, so it sounds like you have some exciting plans for FIG. ForImage has been more of a side project for me on free time.

Looking forward to FIG. ;)
