### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by perazz** [AnonMiraj/fig#22]
List of miscellaneous improvements that I'm seeing on the current repository 

- wherever possible, define `pure elemental` functions: 

https://github.com/AnonMiraj/fig/blob/36c15fac34c156fb1dd40369e0b9a1cab0a695a6/src/fig_rgb.f90#L15-L23 

- Functions that are type initializers should go in an initializer interface: 

https://github.com/AnonMiraj/fig/blob/36c15fac34c156fb1dd40369e0b9a1cab0a695a6/src/fig_rgb.f90#L25-L32 

i.e. something like

``` fortran
interface RGB
   module procedure int_to_rgb
end interface

! So you can define your RGBs as 
my_color = RGB(pixel_int)
```

- Use `i0` format to avoid spaces when printing integers: 

https://github.com/AnonMiraj/fig/blob/36c15fac34c156fb1dd40369e0b9a1cab0a695a6/src/fig_rgb.f90#L41

- Put class functions inside the derived type: 
https://github.com/AnonMiraj/fig/blob/36c15fac34c156fb1dd40369e0b9a1cab0a695a6/src/fig_rgb.f90#L5-L11

```
type(mytype)
...
contains
   procedure, non_overridable :: to_int => rgb_to_int
end type
```

cc @everythingfunctional @johandweber

**Comment by everythingfunctional** [comment]
> * Put class functions inside the derived type:

I'm actually starting to move away from this unless polymorphism is actually going to be used. It feels like a nicer syntax and less namespace pollution, but I'm less and less convinced it's worth it to couple to a language/design feature that you aren't actually taking advantage of.

The rest I pretty well agree with.
