### ISSUE TITLE
License

### ISSUE THREAD

**Issue by johandweber** [AnonMiraj/fig#3]
Hallo,

so far your library does not indicate its license.

The license is not only important for the users but also with respect to what code can be used by the licence.

For example, LGPL code can not be copied/adapted into a public domain library.

Furthermore, it may also be relevant for possible contributors.

In case the library is aimed to be the combined work of a group (for example, in the context of GSoC) you should coordinate with the rest of the team. Else the code is your own and you can decide.

Yours,
Johann

**Comment by AnonMiraj** [comment]
I was thinking of discussing that with my mentor if I get accepted into GSoC, but there would be no harm in settling on MIT. 
Thank you.
