### ISSUE TITLE
Area filling

### ISSUE THREAD

**Issue by johandweber** [AnonMiraj/fig#4]
Hello,

I really like your new triangle examples.

In my opinion it would be useful to add an general area filling subroutine where alk contiguous pixels of the same color are recolorized. This might be useful for irregular shapes, which occur, for example, in geographical maps.

If you think that this makes aense, Iwould like to help and maybe create a pull request within the next week.

Yours,
Johann

**Comment by AnonMiraj** [comment]
Hello Johann,

Absolutely! I can't wait to see it. It will be quite useful in other subroutines. I was thinking of doing something similar in a "fill polygon" subroutine.

Best regards,
Ezz

**Comment by johandweber** [comment]
I have now generated a pull request with that adds a area filling method.

So far, I don't think that it is programmed in a very efficient way (especially with
respect to its memory usage), but it works...

**Comment by AnonMiraj** [comment]
I deleted your flood fill code in the last PR #28. I'm not sure how it will fit in the current design because of how SVG works. If you have any ideas, please let me know.

**Comment by johandweber** [comment]
Hallo, 
the floodfill algorithm really only works for pixel-based images. Unfortunately I do not know if and in which way such functionality can be implemented in SVG or other vector formats.

In the next two weeks my availability is unfortunately rather bad, but I might have a look at it later.
