### ISSUE TITLE
fig_draw_pixel

### ISSUE THREAD

**Issue by johandweber** [AnonMiraj/fig#6]
Hello,

i noted, that the color used in the argument list of fig_draw_pixel is represented by an integer,
whereas the colors of all other drawing operations are of type RGB.

I understand that this is very likely done for performance reasons, and I think the subroutine is well implemented, 
but maybe the name of the  subroutine should somehow reflect that it treats colors in a different way.

Yours,
Johann

**Comment by AnonMiraj** [comment]
Oh, that makes sense. 

Yes, it was for performance reasons. repeatedly converting color from RGB to integer wouldn't be efficient if it was used in a large subroutine with multiple calls.

Should I change it to something like hex_color or color_i?

I'll also update the name in all the relevant subroutines accordingly.
thank you.

**Comment by johandweber** [comment]
Maybe rename the method to

fig_draw_pixel_i

But this is just a suggestion. I do not have clear preferences.

**Comment by AnonMiraj** [comment]
okay seems reasonable
